# -*- coding: utf-8 -*-
"""atividade10.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CeS_-3KpTGAL5vYVA0fnxGjCRvAVULhn
"""

def eh_primo(numero):
 if numero <= 1:
  return False
 for i in range(2, int(numero ** 0.5) + 1):
  if numero % i == 0:
    return False
 print(numero, " é um número primo!")

numero1 = int(input("Digite um numero: "))
numero2 = int(input("Digite um segundo numero: "))

if numero1 > numero2:
  numero3 = numero1 # armazena o numero maior
  numero1 = numero2 # numero menor vai para variavel 1
  numero2 = numero3 # numero maior, armazenado, vai para variavel 2

for i in range(numero1, numero2 + 1):
  eh_primo(i)