# -*- coding: utf-8 -*-
"""atividade5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CeS_-3KpTGAL5vYVA0fnxGjCRvAVULhn
"""

for i in range(1, 11):
  if i % 2 == 0:
    print(i)