# -*- coding: utf-8 -*-
"""atividade7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CeS_-3KpTGAL5vYVA0fnxGjCRvAVULhn
"""

lista_de_compras = []

while True:
  item = input("Digite o item para inserção sua listagem ou SAIR para sair:")
  if item.lower() == "sair":
    break
  lista_de_compras.append(item)

print("Aqui está sua listagem de compras final: ")
for item in lista_de_compras:
  print(item)