# -*- coding: utf-8 -*-
"""atividade3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CeS_-3KpTGAL5vYVA0fnxGjCRvAVULhn
"""

numero1 = int(input("Digite um número: "))
numero2 = int(input("Digite um número: "))

soma = numero1 + numero2
subtracao = numero1 - numero2
produto = numero1 * numero2

if(numero1 == 0 or numero2 == 0):
  divisao = "não é possível realizar divisão por 0"
else:
  divisao = numero1 / numero2

print("Soma:", soma)
print("Subtracao:", subtracao)
print("Produto:", produto)
print("Divisao:", divisao)