# -*- coding: utf-8 -*-
"""atividade2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CeS_-3KpTGAL5vYVA0fnxGjCRvAVULhn
"""

filme = input("Qual é o seu filme favorito? ")
ano = input("Qual o ano de lançamento deste filme? ")
print("O filme favorito deste usuário é, " + filme + "! Ele foi lançado no ano de " + ano + ".") # Imprime a mensagem