# -*- coding: utf-8 -*-
"""atividade9.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CeS_-3KpTGAL5vYVA0fnxGjCRvAVULhn
"""

frase = input("Digite uma frase de sua preferência: ")
letra_desejada = input("Digite uma letra de sua preferência: ")
contador = 0

for letra in frase:
  if letra.lower() == letra_desejada.lower():
    contador += 1

print("A letra desejada apareceu um total de: ", contador)