# -*- coding: utf-8 -*-
"""atividade1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CeS_-3KpTGAL5vYVA0fnxGjCRvAVULhn
"""

print("Meu nome é Ramon e sou natural do Rio de Janeiro (Carioca ;)")