# -*- coding: utf-8 -*-
"""atividade4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CeS_-3KpTGAL5vYVA0fnxGjCRvAVULhn
"""

temperatura = int(input("Digite a temperatura atual em sua localidade: "))
if temperatura > 30:
 print("Tá calor, tá quentinho.")
elif temperatura < 15:
 print("Fio do taaaaio!!!")
else:
  print("Clima agradável, coisa boa ...")