# -*- coding: utf-8 -*-
"""atividade13.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CeS_-3KpTGAL5vYVA0fnxGjCRvAVULhn
"""

soma_total = 0
for i in range(1, 101):
  if i % 2 == 0:
    soma_total += i

print(soma_total)