# -*- coding: utf-8 -*-
"""atividade20.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CeS_-3KpTGAL5vYVA0fnxGjCRvAVULhn
"""

lista_numero = []
soma_total = 0
quantidade = 0
comparativo_maior = 0
comparativo_menor = 9999

while True:
  numero = int(input("Digite um número para ser inserido na listagem de números:" ))
  lista_numero.append(numero)
  escolha = input("Digite SAIR para encerrar ou qualquer coisa coisa para continuar: ")

  if escolha.lower() == "sair":
    break

for numero in lista_numero:
  soma_total += numero
  quantidade += 1

  if numero > comparativo_maior:
    comparativo_maior = numero

  if numero < comparativo_menor:
    comparativo_menor = numero

print("A média dos valores inseridos na listagem é de: ", soma_total/quantidade)
print("O maior número contido na listagem é: ", comparativo_maior)
print("O menor número contido na listagem é: ", comparativo_menor)