# -*- coding: utf-8 -*-
"""atividade8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CeS_-3KpTGAL5vYVA0fnxGjCRvAVULhn
"""

numero = int(input("Digite a quantidade de termos da sequência de Fibonacci desejada: "))

fibonacci = [0, 1]

for i in range(2, numero):
    proximo_termo = fibonacci[-1] + fibonacci[-2]
    fibonacci.append(proximo_termo)

print(f"Os primeiros {numero} termos da sequência de Fibonacci são: {fibonacci[:n]}")