# -*- coding: utf-8 -*-
"""atividade12.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CeS_-3KpTGAL5vYVA0fnxGjCRvAVULhn
"""

from random import randint

escolha = randint(0, 100)

while True:

  escolha_usuario = int(input("Digite um número para tentar acertar o número aleatório: "))

  if escolha_usuario == escolha:
    print("Você acertou!")
    break
  elif escolha_usuario > escolha:
    print("O número que digitou é MAIOR que o aleatório ...")
  else:
    print("O número que digitou é MENOR que o aleatório ...")