# -*- coding: utf-8 -*-
"""atividade2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CeS_-3KpTGAL5vYVA0fnxGjCRvAVULhn
"""

temp_celsius = int(input("Digite a temperatura desejada em CELSIUS: "))
temp_fahrenheit = (temp_celsius * 9 / 5) + 32
temp_kelvin = (temp_celsius + 273.15)


print("A temperatura indicada em celsius convertida para fahrenheit é: ", temp_fahrenheit)
print("A temperatura indicada em celsius convertida para kelvin é: ", temp_kelvin)