# -*- coding: utf-8 -*-
"""atividade10.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CeS_-3KpTGAL5vYVA0fnxGjCRvAVULhn
"""

numero = int(input("Digite um número inteiro: "))

if numero % 2 == 0:
  print("O número digitado é par!")
else:
  print("O número digitado é ímpar!")