# -*- coding: utf-8 -*-
"""atividade16.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CeS_-3KpTGAL5vYVA0fnxGjCRvAVULhn
"""

texto = input("Escreva um texto para invertermos: ")

print("Texto original: ", texto.lower())
print("Texto invertido: ", texto[::-1].lower())