# -*- coding: utf-8 -*-
"""atividade19.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CeS_-3KpTGAL5vYVA0fnxGjCRvAVULhn
"""

nota1 = float(input("Digite a primeira nota (ponderada por 2): ")) * 2
nota2 = float(input("Digite a segunda nota (ponderada por 3): ")) * 3
nota3 = float(input("Digite a terceira nota (ponderada por 5): ")) * 5

print(nota1)
print(nota2)
print(nota3)


media_ponderada = (nota1 + nota2 + nota3) / (2 + 3 + 5)

print("A média ponderada das notas indicadas é: ", media_ponderada)