# -*- coding: utf-8 -*-
"""atividade17.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CeS_-3KpTGAL5vYVA0fnxGjCRvAVULhn
"""

numero = int(input("Digite um número para verificarmos se o mesmo é perfeito: "))
soma_total = 0

for i in range(1, numero):
  if numero % i == 0:
    soma_total += i

if soma_total == numero:
    print("O número digitado é um número perfeito!")
else:
  print("O número digitado não é um número perfeito ...")