# -*- coding: utf-8 -*-
"""atividade4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CeS_-3KpTGAL5vYVA0fnxGjCRvAVULhn
"""

texto = input("Escreva a palavra ou frase desejada para verificarmos se é um palíndromo: ")
texto_invertido = texto[::-1]

print(texto.lower())
print(texto_invertido.lower())


if texto.lower() == texto_invertido.lower():
  print("A palavra original é um palíndromo!")
else:
  print("A palavra original não é um palíndromo ...")