# -*- coding: utf-8 -*-
"""atividade15.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CeS_-3KpTGAL5vYVA0fnxGjCRvAVULhn
"""

numero = int(input("Digite um número: "))
soma_total = 0

for i in range(1, numero + 1):
  soma_total += i

print("A soma dos primeiros N números naturais é de: ", soma_total)