# -*- coding: utf-8 -*-
"""atividade18.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CeS_-3KpTGAL5vYVA0fnxGjCRvAVULhn
"""

texto = input("Digite uma frase: ")
texto_separado = texto.split()
soma_total = 0

for palavra in texto_separado:
  soma_total += 1

print("O texto fornecido possui um total de palavras de: ", soma_total)