# -*- coding: utf-8 -*-
"""atividade5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CeS_-3KpTGAL5vYVA0fnxGjCRvAVULhn
"""

numero = int(input("Digite um número para ver sua tabuada até x 10: "))

for i in range(1, 11):
    print(numero, i, numero*i)