# -*- coding: utf-8 -*-
"""atividade3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CeS_-3KpTGAL5vYVA0fnxGjCRvAVULhn
"""

print("Digite abaixo seu peso e altura, usando . como virgula (ex: 1.75 , 75.5, etc)")
peso = float(input("Digite seu peso para calcularmos seu IMC: "))
altura = float(input("Digite sua altura para calcularmos seu IMC: "))

imc = peso / (altura ** 2)

print(f"IMC CALCULADO: {imc:.2f}")