# -*- coding: utf-8 -*-
"""atividade1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CeS_-3KpTGAL5vYVA0fnxGjCRvAVULhn
"""

numero = int(input("Digite o número desejado para calcular o fatorial: "))
resultado = 1

for i in range(numero, 0, -1):
    resultado *= i

print("O fatorial do numero indicado é: ", resultado)