# -*- coding: utf-8 -*-
"""atividade11.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CeS_-3KpTGAL5vYVA0fnxGjCRvAVULhn
"""

raio_circulo = int(input("Digite o raio para calcularmos a área de um círculo: "))

print("A área do círculo é de: ", (raio_circulo ** 2) * 3.14 )