# -*- coding: utf-8 -*-
"""atividade7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CeS_-3KpTGAL5vYVA0fnxGjCRvAVULhn
"""

nota = 0
soma_nota = 0
quantidade_nota = 0

while nota != -1:
  nota = int(input("Digite a nota desejada para calcularmos a media. Digite -1 para encerrar: "))
  if nota == -1:
    break
  else:
    soma_nota += nota
    quantidade_nota += 1

if quantidade_nota > 0:
  print("A média de todas as notas digitadas é de: ", soma_nota/quantidade_nota)
  print("A quantidade de notas digitadas foi de: ", quantidade_nota)
else:
  print("Nenhuma nota digitada, encerrando programa.")