# -*- coding: utf-8 -*-
"""atividade9.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CeS_-3KpTGAL5vYVA0fnxGjCRvAVULhn
"""

num1 = float(input("Digite o primeiro número: "))
num2 = float(input("Digite o segundo número: "))
num3 = float(input("Digite o terceiro número: "))

if num1 <= num2 and num1 <= num3:
    if num2 <= num3:
        menor, meio, maior = num1, num2, num3
    else:
        menor, meio, maior = num1, num3, num2
elif num2 <= num1 and num2 <= num3:
    if num1 <= num3:
        menor, meio, maior = num2, num1, num3
    else:
        menor, meio, maior = num2, num3, num1
else:
    if num1 <= num2:
        menor, meio, maior = num3, num1, num2
    else:
        menor, meio, maior = num3, num2, num1

print(f"Os números em ordem crescente são: {menor}, {meio}, {maior}")